<a href="https://colab.research.google.com/github/Umeshahnn/Machine_Learning/blob/main/Lab6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# ---- IRIS DATASET ----
iris = pd.read_csv("/content/iris (1).csv")
X = iris.iloc[:, :-1]
y = iris.iloc[:, -1]
Xtr,Xte,ytr,yte = train_test_split(X,y,test_size=0.2,random_state=0)

model = DecisionTreeClassifier()
model.fit(Xtr,ytr)
pred = model.predict(Xte)
print("IRIS Accuracy:",accuracy_score(yte,pred))
print("IRIS Confusion Matrix:\n",confusion_matrix(yte,pred))

# ---- DRUG DATASET ----
drug = pd.read_csv("/content/drug.csv")
le = LabelEncoder()
for c in drug.columns:
    if drug[c].dtype=="object": drug[c]=le.fit_transform(drug[c])

X = drug.drop("Drug",axis=1)
y = drug["Drug"]
Xtr,Xte,ytr,yte = train_test_split(X,y,test_size=0.2,random_state=0)

model = DecisionTreeClassifier()
model.fit(Xtr,ytr)
pred = model.predict(Xte)
print("\n")
print("Drug Accuracy:",accuracy_score(yte,pred))
print("Drug Confusion Matrix:\n",confusion_matrix(yte,pred))

IRIS Accuracy: 1.0
IRIS Confusion Matrix:
 [[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


Drug Accuracy: 1.0
Drug Confusion Matrix:
 [[ 3  0  0  0  0]
 [ 0  1  0  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0 14  0]
 [ 0  0  0  0 19]]


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

# Load dataset
data = pd.read_csv("/content/petrol_consumption.csv")

# Features and target
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

# 80% training, 20% testing
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

# Regression Tree model
model = DecisionTreeRegressor()
model.fit(X_train,y_train)

# Prediction
y_pred = model.predict(X_test)

# Evaluation
mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

print("Mean Absolute Error:",mae)
print("Mean Squared Error:",mse)
print("Root Mean Squared Error:",rmse)

Mean Absolute Error: 52.3
Mean Squared Error: 4698.9
Root Mean Squared Error: 68.54852296001715
